// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4089.Stealth2018.commands;
import org.usfirst.frc4089.Stealth2018.Robot;

import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.Joystick;

/**
 *
 */
public class HugBlock extends Command {
  
    public HugBlock() {
        requires(Robot.picker);
        //System.out.println("RejectBlock");
    }

    protected void initialize() {
      //System.out.println("Init");
    	Robot.logging.LogEvent("Hug Block Source: Commands.HugBlock");
    }

    protected void execute() {
      System.out.println("Close picker");
    	Robot.picker.hugBlock();
    }

    protected boolean isFinished() {
        return true;
    }

    protected void end() {
    	
    }

    protected void interrupted() {
      end();
    }
}
