// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4089.Stealth2018.commands;
import org.usfirst.frc4089.Stealth2018.Robot;
import org.usfirst.frc4089.Stealth2018.RobotMap;

import edu.wpi.first.wpilibj.command.Command;

public class LowerPickerToBottom extends Command {
  
    public LowerPickerToBottom() {
    	requires(Robot.elevator);
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    	Robot.logging.LogEvent("LowerPickerToBottom Source: Commands.LowerPickerToBottom");
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	if (RobotMap.overridePickerElevator) {
    		System.out.println("Lower Elevator OVERRIDE MODE");
    	    RobotMap.pickerElevatorMotor.set(-0.8);
    	} else {
    		System.out.println("Lower Elevator PID MODE");
    		Robot.elevator.SetPickerElevatorTarget(0);
    	}
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
    	return !RobotMap.overridePickerElevator || RobotMap.pickerElevatorSensors.isRevLimitSwitchClosed();
    }

    // Called once after isFinished returns true
    protected void end() {
      if (RobotMap.overridePickerElevator) {
    	  RobotMap.pickerElevatorMotor.set(0);
      } else {
    	  //do nothing
      }
    	
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
      end();
    }
}
