// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4089.Stealth2018.commands;
import org.usfirst.frc4089.Stealth2018.Robot;
import org.usfirst.frc4089.Stealth2018.RobotMap;
import org.usfirst.frc4089.Stealth2018.utilities.StopWatch;

import edu.wpi.first.wpilibj.command.Command;

/**
 *
 */
public class LowerPicker extends Command {
  
    StopWatch mWaitTime = new StopWatch(1100);

    
    public LowerPicker() {
        requires(Robot.picker);
    }

    // Called just before this Command runs the first time
    protected void initialize() {
      mWaitTime.reset();
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
      Robot.picker.setRaisePickerMotor(-0.7);
    }

    protected boolean isFinished() {
      
        return (mWaitTime.timeLeft() <= 0);
    }

    // Called once after isFinished returns true
    protected void end() {
    	Robot.picker.setRaisePickerMotor(0);
    }

    protected void interrupted() {
      end();
    }
}
