// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4089.Stealth2018.commands;
import org.usfirst.frc4089.Stealth2018.Constants;
import org.usfirst.frc4089.Stealth2018.Robot;
import org.usfirst.frc4089.Stealth2018.RobotMap;

import edu.wpi.first.wpilibj.command.Command;

/**
 *
 */
public class RotateClimberMotorReverse extends Command {

    
    public RotateClimberMotorReverse() {
        requires(Robot.climb);
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    	Robot.logging.LogEvent("RotateClimberMotorReverse Source: Commands.RotateClimberMotorReverse");
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	Robot.climb.SetClimberMotor(Constants.climbMotorPowerLower);
    }

    protected boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    protected void end() {
    	Robot.climb.SetClimberMotor(0);
    }

    protected void interrupted() {
      end();
    }
}
