// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4089.Stealth2018.commands;

import org.usfirst.frc4089.Stealth2018.Robot;
import org.usfirst.frc4089.Stealth2018.RobotMap;

import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.command.PIDCommand;

/**
 *
 */
public class UserManualPickerElevator extends Command {
    public UserManualPickerElevator() {
    	requires(Robot.elevator);
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
      //Robot.elevator.MoveElevatorToTarget();
    	//Robot.elevator.DriveElevator(Robot.oi.driveJoystick);
    	
    	if (Robot.oi.mechJoystick.getRawAxis(1) > 0) {
    		Robot.elevator.MovePickerElevator(1);
    	} else if (Robot.oi.mechJoystick.getRawAxis(1) < 0) {
    		Robot.elevator.MovePickerElevator(-1);
    	} else {
    		Robot.elevator.MovePickerElevator(0);
    	}
    	
    	
    	//double motorOutput = Robot.oi.mechJoystick.getRawAxis(1);
    	
    	//Robot.elevator.MovePickerElevator(motorOutput); 
    	
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return RobotMap.pickerElevatorSwitchTop.get() || RobotMap.pickerElevatorSwitchBottom.get();
    }

    // Called once after isFinished returns true
    protected void end() {
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    	end();
    }
}
