
arduinocomm:	ArduinoComm.cpp StopWatch.cpp
	g++ ArduinoComm.cpp StopWatch.cpp -o ArduinoComm -std=c++11 -I../ntcore-master/wpiutil/include -I../ntcore-master/include -lpthread -L../ntcore-master/bins/ -lntcore -lwiringPi -lstdc++
