// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4089.Stealth2018.subsystems;

import org.usfirst.frc4089.Stealth2018.Constants;
import org.usfirst.frc4089.Stealth2018.RobotMap;
import org.usfirst.frc4089.Stealth2018.commands.*;

import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class Climb extends Subsystem {

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
    }
    

    public void grabClimber () {
      RobotMap.climberGrabber.set(true);
      
      //System.out.println("Grab Climber Source: Picker.grabClimber()");
    }

    public void ungrabClimber() {
      RobotMap.climberGrabber.set(false);
      
      //System.out.println("Ungrab Climber Source: Picker.ungrabClimber()");
    }
    
    /*public void raiseClimber () {
    	RobotMap.climbMotor.set(Constants.climbMotorPowerRaise);
    }
    
    public void lowerClimber () {
    	RobotMap.climbMotor.set(Constants.climbMotorPowerLower);
    }*/
    
    public void SetClimberMotor (double value) {
    	RobotMap.climbMotor.set(value);
    }
    
  
    

}

