// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4089.Stealth2018.subsystems;

<<<<<<< HEAD
import org.usfirst.frc4089.Stealth2018.Robot;
=======
import org.usfirst.frc4089.Stealth2018.Constants;
>>>>>>> parent of ec557f8... Merge branch 'master' of https://github.com/Stealth-Robotics/Stealth2018
import org.usfirst.frc4089.Stealth2018.RobotMap;
import org.usfirst.frc4089.Stealth2018.commands.*;
import org.usfirst.frc4089.Stealth2018.subsystems.Drive.DriveControlState;
import org.usfirst.frc4089.Stealth2018.utilities.DriveMath;

import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;
import edu.wpi.first.wpilibj.CounterBase.EncodingType;
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.Encoder;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.PIDController;
import edu.wpi.first.wpilibj.PIDSourceType;
import edu.wpi.first.wpilibj.smartdashboard.*;

import edu.wpi.first.wpilibj.command.Subsystem;

public class Elevator extends Subsystem {
    private int elevatorTargetTick;
    private int pickerElevatorTargetTick;
  	private int pidElevatorTarget;
  	private int pidPickerElevatorTarget;

<<<<<<< HEAD
  //--------------------------------------------------------------------
  // Purpose:
  //     Sets the default command 
  //
  // Notes:
  //     none
  //--------------------------------------------------------------------  
  public void initDefaultCommand() {
    setDefaultCommand(new UserElevator());
  }
    
  //--------------------------------------------------------------------
  // Purpose:
  //     Drive using the joystick 
  //
  // Notes:
  //     none
  //--------------------------------------------------------------------  
  public void DriveElevator(Joystick driveJoystick) {
    
    if (driveJoystick.getRawButton(9) || Robot.oi.dsJoystick.getRawButton(5)) {
      RobotMap.overrideElevator = true;
=======
	
    public void initDefaultCommand() {
      setDefaultCommand(new UserElevator());
>>>>>>> parent of ec557f8... Merge branch 'master' of https://github.com/Stealth-Robotics/Stealth2018
    }
    
    //--------------------------------------------------------------------
    // Purpose:
    //     Drive using the joystick 
    //
    // Notes:
    //     none
    //--------------------------------------------------------------------  
    public void DriveElevator(Joystick driveJoystick) {
      HandleElevator(driveJoystick.getRawAxis(1));
      HandlePickerElevator(driveJoystick.getRawAxis(5));
    }
    
      //--------------------------------------------------------------------
      // Purpose:
      //     Drive using the joystick 
      //
      // Notes:
      //     none
      //--------------------------------------------------------------------  
    public void HandleElevator(double yElevator) {
	  boolean elevatorSwitchTop = RobotMap.elevatorSwitchTop.get();
	  boolean elevatorSwitchBottom = RobotMap.elevatorSwitchBottom.get();
		  
	  yElevator = DriveMath.DeadBand(yElevator, 0.25);
	
	  if(true == elevatorSwitchBottom)
	  {
	    // If the elevator is at the bottom and we want to go down, don't
	    if(yElevator > 0)
	    {
	      yElevator = 0;
	    }
	  }
	  else
	  {
	    if(true == elevatorSwitchTop)
	    {
	      if(yElevator < 0)
	      {
	        yElevator = 0;
	      }
	    }
	  }
	  
	  elevatorTargetTick += yElevator * 10;
	  	 
	  SetElevatorTarget(elevatorTargetTick);
    }   
 
      //--------------------------------------------------------------------
      // Purpose:
      //     Drive using the joystick 
      //
      // Notes:
      //     none
      //--------------------------------------------------------------------  
    public void HandlePickerElevator(double yElevator) {
    	boolean elevatorSwitchTop = RobotMap.pickerElevatorSwitchTop.get();
        boolean elevatorSwitchBottom = RobotMap.pickerElevatorSwitchBottom.get();
      
      yElevator = DriveMath.DeadBand(yElevator,0.25);

      if(true == elevatorSwitchBottom)
      {
        if(yElevator > 0)
        {
          yElevator = 0;
        }
      }
      else
      {
        if(true == elevatorSwitchTop)
        {
          if(yElevator < 0)
          {
            yElevator = 0;
          }
        }
      }

	  pickerElevatorTargetTick += yElevator * 10;

	  SetPickerElevatorTarget(pickerElevatorTargetTick);
<<<<<<< HEAD
=======
    HandleElevator(driveJoystick.getRawAxis(1));
    HandlePickerElevator(driveJoystick.getRawAxis(5));
  }
    
  //--------------------------------------------------------------------
  //--------------------------------------------------------------------
  //--------------------------------------------------------------------
  // Main Elevator Functions
  //--------------------------------------------------------------------
  //--------------------------------------------------------------------
  //--------------------------------------------------------------------
  // --------------------------------------------------------------------
  // Constants:
  // --------------------------------------------------------------------
  final double elevatorKp = 0.035;
  final double elevatorKi = 0.00069;
  final double elevatorKd = 0;

=======
    }
>>>>>>> parent of ec557f8... Merge branch 'master' of https://github.com/Stealth-Robotics/Stealth2018
  

<<<<<<< HEAD
  
  //--------------------------------------------------------------------
  // Purpose:
  //     Drive elevator using the joystick 
  //
  // Notes:
  //     none
  //--------------------------------------------------------------------  
  private void HandleElevator(double yElevator) {
    yElevator = DriveMath.DeadBand(yElevator, 0.20);
    int change = (int)(-yElevator * 10);
    boolean topSwitch = RobotMap.elevatorSwitchTop.get();
    boolean bottomSwitch = RobotMap.elevatorSwitchBottom.get();
    
    if (RobotMap.overrideElevator) {
      
      if(topSwitch) {
        if(-yElevator > 0) {
          yElevator = 0;
        }
      }
      
      if (bottomSwitch) {
        if (-yElevator < 0) {
          yElevator = 0;
        }
      }
      
      RobotMap.elevatorMotor.set(-yElevator);
    } else {
      // only change things if the user wants to to advoid messing with auto
      if(0 != change)
      {
        // if nothing is pressed move the elevator
        if((false == topSwitch)&&
            (false == bottomSwitch))
        {
          AddElevatorTarget(change);
        }
        else
        {  
          // Don't change the drive if the switches are set
          if((true == bottomSwitch)&&
              (change>0))
           {
             AddElevatorTarget(change);
           }
          else
          {
              if(change<0)
             {
               AddElevatorTarget(change);
             }
          }
        }
      }
>>>>>>> 61c50d4562c4505468a39dfc9c7d636ea68fdfef
    }
  }   
 
  //--------------------------------------------------------------------
  // Purpose:
  //     Sets the elevator to a known position 
  //
  // Notes:
  //     none
  //--------------------------------------------------------------------  
  public void SetElevatorTarget(int target)
  {
    pidElevatorTarget = target;  
  }
    
  //--------------------------------------------------------------------
  // Purpose:
  //     Adds an amount to the current position 
  //
  // Notes:
  //     none
  //--------------------------------------------------------------------  
  public void AddElevatorTarget(int amount)
  {
    pidElevatorTarget += amount;  
  }
    
  //--------------------------------------------------------------------
  // Purpose:
  //     Get Elevator Current Posiotn 
  //
  // Notes:
  //     none
  //--------------------------------------------------------------------  
  public int GetElevatorPosition() {
<<<<<<< HEAD
	
	int currentElevatorEncoderValue = RobotMap.elevatorEncoder.get();
	
	if (currentElevatorEncoderValue == 0) {
		System.out.println("Elevator Encoder has Zero Value");
	} else if (currentElevatorEncoderValue == lastElevatorEncoderValue) {
		System.out.println("Encoder Value has not changes since last update");
	} else {
		elevatorEncoderValue = currentElevatorEncoderValue;
=======
  	public void SetElevatorTarget(int target) {
		pidElevatorTarget = target;
>>>>>>> parent of ec557f8... Merge branch 'master' of https://github.com/Stealth-Robotics/Stealth2018
	}
  
  	
  final double elevatorKPconst = 0.01;
  public void MoveElevatorToTarget() {
	  //get limit switches
	  boolean elevatorSwitchTop = RobotMap.elevatorSwitchTop.get();
      boolean elevatorSwitchBottom = RobotMap.elevatorSwitchBottom.get();
      //reset encoder if at bottom switch
	  if (elevatorSwitchBottom == true) {
    	  RobotMap.elevatorEncoder.reset();
      }
	  //get current ticks
	  int elevatorEncoderTicks = RobotMap.elevatorEncoder.get();
	  //calculate error
	  double error = pidElevatorTarget - elevatorEncoderTicks;
	  //set the motor power
	  double motorOutput = error * elevatorKPconst;
	  //clamp the value between -1 and 1
	  motorOutput = Math.max(-1, Math.min(1, motorOutput));
	  //make sure it doesn't go past limit switches
	  if (elevatorSwitchBottom == true && motorOutput < 0) {
		  motorOutput = 0;
	  }
	  
	  if (elevatorSwitchTop == true && motorOutput > 0) {
		  motorOutput = 0;
	  }
<<<<<<< HEAD
	  
	  System.out.println("elevatorEncoderCount : " + elevatorEncoderCount);
	  
<<<<<<< HEAD
=======
	
	lastElevatorEncoderValue = currentElevatorEncoderValue;
	
    return elevatorEncoderValue;
    
=======
    return RobotMap.elevatorEncoder.get();
>>>>>>> parent of 61c50d4... Merge branch 'master' of https://github.com/Stealth-Robotics/Stealth2018
   }
  //--------------------------------------------------------------------
  // Purpose:
  //     Runs the motion control on the elevator 
  //
  // Notes:
  //     none
  //--------------------------------------------------------------------  
  public void MoveElevatorToTarget() {
    //get current ticks
    int elevatorEncoderTicks = RobotMap.elevatorEncoder.get();

    //make sure it doesn't go past limit switches
    if (RobotMap.elevatorSwitchBottom.get() == true) {
      RobotMap.elevatorEncoder.reset();
      
      SetElevatorTarget(25);
      elevatorIntegral = 0.0;
      elevatorPreviousError = 0.0;
    }
    
    if (RobotMap.elevatorSwitchTop.get() == true) {
      SetElevatorTarget(elevatorEncoderTicks-25);
      elevatorIntegral = 0.0;
      elevatorPreviousError = elevatorEncoderTicks;
    }
    
	  //calculate error
	  double error = pidElevatorTarget - elevatorEncoderTicks;
	  //Calculate Motor Power using PID loop
	  elevatorIntegral = elevatorIntegral + error;
	  elevatorIntegral = Math.max(0, Math.min(1440, elevatorIntegral));
	  double derivative = (error - elevatorPreviousError);
	  double motorOutput = elevatorKp*error + elevatorKi*elevatorIntegral + elevatorKd*derivative;
	  elevatorPreviousError = error;
	  //clamp the value between -1 and 1
	  motorOutput = Math.max(-1, Math.min(1, motorOutput));
	  
>>>>>>> 61c50d4562c4505468a39dfc9c7d636ea68fdfef
=======
>>>>>>> parent of ec557f8... Merge branch 'master' of https://github.com/Stealth-Robotics/Stealth2018
	  elevatorLastEncoderTicks = elevatorEncoderTicks;
	  
=======
>>>>>>> parent of 83df628... did things so yea
	  //set the motor to the correct value
	  RobotMap.elevatorMotor.set(motorOutput);
	  //Debugin stuff
	  System.out.println("elevatorEncoderTicks: " + elevatorEncoderTicks);
	  System.out.println("elevatorMotorPower: " + RobotMap.elevatorMotor.get());
 }
<<<<<<< HEAD
=======

	  RobotMap.netTable.putNumber("elevatorMotorOutput", motorOutput);
    RobotMap.netTable.putNumber("elevatorError", error);
    RobotMap.netTable.putNumber("elevatorSetPoint", pidElevatorTarget);
    RobotMap.netTable.putNumber("elevatorIntegral", elevatorIntegral);
    RobotMap.netTable.putNumber("elevatorDerivative", derivative);
  }

  //--------------------------------------------------------------------
  //--------------------------------------------------------------------
  //--------------------------------------------------------------------
  // Picker Elevator Functions
  //--------------------------------------------------------------------
  //--------------------------------------------------------------------
  //--------------------------------------------------------------------

  // --------------------------------------------------------------------
  // Constants:
  // --------------------------------------------------------------------
  final double pickerElevatorKp = 0.03;
  final double pickerElevatorKi = 0;
  final double pickerElevatorKd = 0;

  // --------------------------------------------------------------------
  // Attributes:
  // --------------------------------------------------------------------
  private int pidPickerElevatorTarget;
  double pickerElevatorPreviousError = 0;
  double pickerElevatorIntegral = 0;
  double pickerElevatorLastEncoderTicks = 0;
  double pickerElevatorEncoderCount = 0;
  
  //--------------------------------------------------------------------
  // Purpose:
  //     Sets the setpoint from the joystick 
  //
  // Notes:
  //     none
  //--------------------------------------------------------------------  
  private void HandlePickerElevator(double yElevator) {
    yElevator = DriveMath.DeadBand(yElevator,0.25);
    int change = (int)(-yElevator * 10);
    boolean topSwitch = RobotMap.pickerElevatorSwitchTop.get();
    boolean bottomSwitch = RobotMap.pickerElevatorSwitchBottom.get();
    
    if (RobotMap.overridePickerElevator) {
      
      if(topSwitch) {
        if(-yElevator > 0) {
          yElevator = 0;
        }
      }
      
      if (bottomSwitch) {
        if (-yElevator < 0) {
          yElevator = 0;
        }
      }
      
      RobotMap.pickerElevatorMotor.set(-yElevator);
    } else {
      // only change things if the user wants to to advoid messing with auto
      if(0 != change)
      {
        // if nothing is pressed move the elevator
        if((false == topSwitch)&&
            (false == bottomSwitch))
        {
          AddPickerElevatorTarget(change);
        }
        else
        {  
          // Don't change the drive if the switches are set
          if((true == bottomSwitch)&&
              (change>0))
           {
             AddPickerElevatorTarget(change);
           }
          else
          {
              if(change<0)
             {
               AddPickerElevatorTarget(change);
             }
          }
        }
      }
    }
  }
>>>>>>> 61c50d4562c4505468a39dfc9c7d636ea68fdfef
=======
>>>>>>> parent of ec557f8... Merge branch 'master' of https://github.com/Stealth-Robotics/Stealth2018
 
 public void SetPickerElevatorTarget(int target) {
 	pidPickerElevatorTarget = target;
 }

 final double pickerElevatorKPconst = 0.01;
 public void MovePickerElevatorToTarget() {
	 //get limit switches
	 boolean elevatorSwitchTop = RobotMap.pickerElevatorSwitchTop.get();
     boolean elevatorSwitchBottom = RobotMap.pickerElevatorSwitchBottom.get();
     //reset encoder if at bottom switch
	  if (elevatorSwitchBottom == true) {
   	  RobotMap.pickerElevatorEncoder.reset();
     }
	  //get current ticks
	  int pickerElevatorEncoderTicks = RobotMap.pickerElevatorEncoder.get();
	  //calculate error
	  double error = pidPickerElevatorTarget - pickerElevatorEncoderTicks;
	  //set the motor power
	  double motorOutput = error * pickerElevatorKPconst;
	  //clamp the value between -1 and 1
	  motorOutput = Math.max(-1, Math.min(1, motorOutput));
	  //make sure it doesn't go past limit switches
	  if (elevatorSwitchBottom == true && motorOutput < 0) {
		  motorOutput = 0;
	  }
	  
	  if (elevatorSwitchTop == true && motorOutput > 0) {
		  motorOutput = 0;
	  }
	  //set the motor to the correct value
	  RobotMap.pickerElevatorMotor.set(motorOutput);
	  //Debugin stuff
	  System.out.println("pickerElevatorEncoderTicks: " + pickerElevatorEncoderTicks);
	  System.out.println("pickerElevatorMotorPower: " + RobotMap.pickerElevatorMotor.get());
	 
	 /*boolean elevatorSwitchTop = RobotMap.pickerElevatorSwitchTop.get();
     boolean elevatorSwitchBottom = RobotMap.pickerElevatorSwitchBottom.get();
     
     if (elevatorSwitchBottom == true) {
    	 RobotMap.pickerElevatorEncoder.reset();
     }
	 
	 // when -100000, lower until bottom limit 2 == true
	 
	  int pickerElevatorEncoderTicks = RobotMap.pickerElevatorEncoder.get();
	  if(pidPickerElevatorTarget == pickerElevatorEncoderTicks)
	  {
		  RobotMap.pickerElevatorMotor.set(0);
	  }
	  if(pidPickerElevatorTarget < pickerElevatorEncoderTicks)
	  {
		  RobotMap.pickerElevatorMotor.set(1);
	  }
	  else if(pidPickerElevatorTarget > pickerElevatorEncoderTicks)
	  {
		  RobotMap.pickerElevatorMotor.set(-1);
	  }
<<<<<<< HEAD
=======
/*
   if (RobotMap.pickerElevatorSwitchBottom.get() == true) {
     RobotMap.pickerElevatorEncoder.reset();
     SetPickerElevatorTarget(0);
     pickerElevatorIntegral = 0.0;
     pickerElevatorPreviousError = 0.0;
   }
   
   if (RobotMap.elevatorSwitchTop.get() == true) {
     SetPickerElevatorTarget(pickerElevatorEncoderTicks);
     pickerElevatorIntegral = 0.0;
     pickerElevatorPreviousError = pickerElevatorEncoderTicks;
   }
	*/
   
	  //calculate error
	  double error = pidPickerElevatorTarget - pickerElevatorEncoderTicks;
	  //calculate motor output power
	  pickerElevatorIntegral = pickerElevatorIntegral + error;
	  pickerElevatorIntegral = Math.max(0, Math.min(1440, pickerElevatorIntegral));
	  double derivative = (error - pickerElevatorPreviousError);
	  double motorOutput = pickerElevatorKp*error + pickerElevatorKi*pickerElevatorIntegral + pickerElevatorKd*derivative;
	  pickerElevatorPreviousError = error;
	  //clamp the value between -1 and 1
	  motorOutput = Math.max(-1, Math.min(1, motorOutput));
	  
	  pickerElevatorLastEncoderTicks = pickerElevatorEncoderTicks;
	  
	  //set the motor to the correct value
<<<<<<< HEAD
	  MovePickerElevator(motorOutput);
>>>>>>> 61c50d4562c4505468a39dfc9c7d636ea68fdfef
=======
	  RobotMap.pickerElevatorMotor.set(motorOutput);
>>>>>>> parent of 61c50d4... Merge branch 'master' of https://github.com/Stealth-Robotics/Stealth2018
	  
	  RobotMap.netTable.putNumber("pickerElevatorMotorOutput", motorOutput);
    RobotMap.netTable.putNumber("pickerError", error);
    RobotMap.netTable.putNumber("pickerSetPoint", pidPickerElevatorTarget);
    RobotMap.netTable.putNumber("pickerElevatorIntegral", pickerElevatorIntegral);
    RobotMap.netTable.putNumber("pickerElevatorDerivative", derivative);
 }

 //--------------------------------------------------------------------
 //--------------------------------------------------------------------
 //--------------------------------------------------------------------
 // Climb Hook Functions
 //--------------------------------------------------------------------
 //--------------------------------------------------------------------
 //--------------------------------------------------------------------
=======
	  
	  System.out.println("pickerElevatorEncoderTicks: " + pickerElevatorEncoderTicks);*/
 } 
   
>>>>>>> parent of ec557f8... Merge branch 'master' of https://github.com/Stealth-Robotics/Stealth2018
 //TODO: Move to it's own command not under the elevator subsystem
  public void EngageClimbHook() {
	  //1. Lower elevator to bottom (limit switch 1 = true)
	  SetElevatorTarget(0);
	  SetPickerElevatorTarget(0);
	  
	  //2. Engage climb hook pneumatic 
	  
	  
	  //3. Lower elevator to retract grabber
	  SetPickerElevatorTarget(-100000); 
	  
	  //4. Engage pneumatic to lock grabber in upright position
	  
	  
	  //5. Return to user drive mode
	  
	  
  }
}

